# Generated by Django 5.0.4 on 2024-05-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_user_balance'),
        ('main', '0016_alter_user_registration_code'),
    ]

    operations = [
    ]
