# Generated by Django 5.0.4 on 2024-05-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_product_total_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credit_remain',
        ),
        migrations.RemoveField(
            model_name='user',
            name='debt',
        ),
    ]
