# Generated by Django 5.0.4 on 2024-05-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_product_total_purchase_user_total_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_purchase',
            field=models.FloatField(default=0),
        ),
    ]
