# Generated by Django 5.0.4 on 2024-05-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_user_total_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Order2',
        ),
    ]
