# Generated by Django 5.0.4 on 2024-05-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='returns',
            name='reason',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
