# Generated by Django 5.0.4 on 2024-05-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_returns_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='product',
            field=models.IntegerField(),
        ),
    ]
