# Generated by Django 5.0.4 on 2024-05-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_returns_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='product',
            field=models.CharField(max_length=255),
        ),
    ]
