# Generated by Django 5.0.4 on 2024-05-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_returns_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
