# Generated by Django 5.0.4 on 2024-05-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_order_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='returns',
            name='document_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returns',
            name='return_document_number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
